openapi: 3.1.0
info:
  title: My API
  description: API for managing products
  version: 1.0.0
  contact:
    email: adam@manuel.dev
    name: Adam Manuel
    url: https://adam.manuel.dev
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://example.com/terms
paths:
  /pet:
    get:
      tags:
        - pet
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      responses:
        "200":
          $ref: "#/components/responses/Created"
          summary: Pet
    post:
      tags:
        - pet
      summary: Update pet by ID
      description: Updated a single pet
      operationId: updatePetById
      requestBody:
        $ref: "#/components/requestBodies/CreatePet"
      responses:
        "200":
          $ref: "#/components/responses/Updated"
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dog"
              example:
                size: 12
                breed: Labrador Retriever
components:
  schemas:
    Dog:
      type: object
      properties:
        size:
          description: The size of the shape.
          minimum: 0
          maximum: 100
          type: integer
        breed:
          type: string
          pattern: ^[A-Za-z\s]+$
          minLength: 1
          maxLength: 100
    Pet:
      type: object
      properties:
        name:
          type: string
          pattern: ^[A-Za-z\s]+$
          minLength: 1
          maxLength: 100
  responses:
    Created:
      description: Object created
      summary: Create
    Updated:
      description: Object updated
      summary: Update
  parameters:
    petId:
      name: id
      in: header
      schema:
        type: string
  examples: {}
  requestBodies:
    CreatePet:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                pattern: ^[A-Za-z\s]+$
                minLength: 1
                maxLength: 100
      description: Create a new pet
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags:
  - name: pet
    description: Operations about pets
servers:
  - url: https://api.example.com
    description: Production server
  - url: https://stg-api.example.com
    description: Staging server
  - url: https://dev-api.example.com
    description: Development server
externalDocs:
  url: https://example.com/docs
  description: Example documentation

